### ISSUE TITLE
Lowercase letter r in Overpass Mono is with serif

### ISSUE THREAD

**Issue by nertpinx** [RedHatBrand/Overpass#47]
Both Overpass and Overpass Mono fonts are sans-serif fonts.  However, I see the lowercase letter r with serifs. I first thought that was a mistake on my part, but seeing Overpass is currently on Google Fonts as well, and it is certainly visible there, and on overpassfont.org as well (see monospaced links in the top part of the page), it looks like it is a problem in the font itself. Looking closely now, it seems letters 'f' and 'l' do as well have such a problem.

**Comment by andyfitz** [comment]
This is by design @nertpinx   The challenge was to provide rendered distinction between glyphs yet strinking a balance to occupy the same horizontal footprint and flow accordingly.

the lowercase characters you see with slabs had to be this way or they would vacate too much realestate.

This is the challenge of monospaced fonts.  at some sizes  it gets really important to tell r from c from ( from { from <

**Comment by davelab6** [comment]
I agree, many monospace fonts have this design

**Comment by nertpinx** [comment]
OK, thanks for the info, it's true.  I haven't realized because I do not find it as disturbing with some other fonts I use.
